### ISSUE TITLE
pyrotorque bad module name

### ISSUE THREAD

**Issue by Aqualie** [kannibalox/pyrosimple#25]
Trying to migrate from pyrocore to pyrosimple. I've finished migrating all of the torque configuration but when I run
**pyrotorque --fg**
I simply get an error:
![vncviewer_2022-12-29_12-54-51](https://user-images.githubusercontent.com/8303616/209990993-075f6018-9138-4fe8-8480-fafb3682b60a.png)

I have all the dependencies installed:
![vncviewer_2022-12-29_12-55-17](https://user-images.githubusercontent.com/8303616/209991029-9f566eca-ba16-4153-bc3a-1adde5797f6e.png)

torque config:
```
## https://github.com/kannibalox/pyrosimple/blob/main/docs/pyrotorque-jobs.md
[TORQUE]
autoreload = true # false by default
[TORQUE.queue]
handler = "pyrocore.torrent.watch:QueueManager"
schedule = "second=*/15"
active = true
dry_run = false
sort_fields = "-prio, loaded, name"
downloading_min = 1
downloading_max = 9
start_at_once = 4
intermission = 0
startable = "is_ignored=0 done=0 message='' prio>0"
[TORQUE.stats]
handler = "pyrocore.torrent.jobs:EngineStats"
schedule = "minute=*"
active = true
dry_run = false
[TORQUE.watch]
handler = "pyrocore.torrent.watch:TreeWatch"
schedule = "second=*/5"
active = true
dry_run = false
load_mode = "start"
queued = true
path = "/mnt/torrent/start"
```

**Comment by kannibalox** [comment]
The handler names have been moved to be under `pyrosimple.job`, give the following config a try:

```toml
## https://github.com/kannibalox/pyrosimple/blob/main/docs/pyrotorque-jobs.md
[TORQUE]
autoreload = true # false by default
[TORQUE.queue]
handler = "pyrocore.job.queue:QueueManager"
schedule = "second=*/15"
active = true
dry_run = false
sort = "-prio,loaded,name"
downloading_min = 1
downloading_max = 9
start_at_once = 4
intermission = 0
startable = "is_ignored=0 done=0 message=\"\" prio>0"
[TORQUE.stats]
handler = "pyrocore.job.metrics:EngineStats"
schedule = "minute=*"
active = true
dry_run = false
[TORQUE.watch]
handler = "pyrocore.job.watch:TreeWatch"
schedule = "second=*/5"
active = true
dry_run = false
load_mode = "start"
# queued = true # No longer has any effect, the below command replicates the behavior
cmd_queue = "d.priority.set=0"
path = "/mnt/torrent/start"
```

Some of the changes (e.g. `sort_fields = "-prio, loaded, name"
` to `sort = "-prio,loaded,name"`) will be allowed in the latest code for backwards compatibility. I've also added a section to the [migration docs](https://kannibalox.github.io/pyrosimple/migrate/#pyrotorque) for posterity.
