### ISSUE TITLE
pyrotorque multiple clients

### ISSUE THREAD

**Issue by TMD20** [kannibalox/pyrosimple#8]
Is it possible to setup per client pyrosimple
jobs

I'm going to try to move my pyrotorque config from pyrocore to pyrosimple
Previously I had two different clients, both with their own config files.

However now everything lives in one config file. So from what I can see all my client have to share the same jobs. Along with the console outputs those jobs bring with them

**Comment by kannibalox** [comment]
If you just need to be able to use a different config.toml for each instance, you can use the `PYRO_CONF` environment variable:
```
PYRO_CONF=~/.config/pyrosimple/client2-config.toml pyrotorque
```

One thing I've been considering is adding a new feature to let a single pyrotorque instance manage multiple clients, e.g. something like
```toml
[TORQUE]                                                                                                                                                                                                                                                                                                                                                                     
[TORQUE.stats]                                                                                                                                                                                                                                                                                                                                                               
handler = "pyrocore.torrent.jobs:EngineStats"                                                                                                                                                                                                                                                                                                                                
schedule = "minute=*"                                                                                                                                                                                                                                                                                                                                                        
client = "local"
[TORQUE.stats]                                                                                                                                                                                                                                                                                                                                                               
handler = "pyrocore.torrent.jobs:EngineStats"                                                                                                                                                                                                                                                                                                                                
schedule = "minute=*"                                                                                                                                                                                                                                                                                                                                                        
client = "seedbox"
```
But that isn't ready yet, and I'm not sure how useful it is versus just having multiple pyrotorques running
